// ----------------------
// Subscriber Model
// ----------------------
export interface Subscriber {
  subscriber_id: number; // Primary key in the DB
  url: string;           // Endpoint URL for the subscriber
  created_at?: Date;     // Optional timestamp, usually auto-generated by DB
}