version: '3.9'

services:
  # -------------------- API --------------------
  api:
    build: .
    container_name: webhook_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    command: ["node", "dist/index.js"]

  # -------------------- WORKER --------------------
  worker:
    build: .
    container_name: webhook_worker
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
      - redis
    command: ["node", "dist/worker/worker.js"]

  # -------------------- SUBSCRIBER --------------------
  subscriber:
    build: .
    container_name: webhook_subscriber
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    command: ["node", "dist/tests/subscriber.js"]

  # -------------------- POSTGRES --------------------
  db:
    image: postgres:16
    container_name: webhook_postgres
    restart: always
    environment:
      POSTGRES_USER: mohammad
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # -------------------- REDIS --------------------
  redis:
    image: redis:7
    container_name: webhook_redis
    restart: always
    ports:
      - "6379:6379"

# -------------------- VOLUMES --------------------
volumes:
  postgres_data: